version: "3"

services:
  # frontend:
  #   container_name: frontend
  #   restart: unless-stopped
  #   build:
  #     context: ./frontend
  #   command: ["yarn", "start"]
  #   ports:
  #     - 3042:3000
  #   volumes:
  #     - ./frontend/:/frontend/
  #     - ./frontend/node_modules/:/frontend/node_modules
  #   environment:
  #     - CI=true
  #     - CHOKIDAR_USEPOLLING=true
  #     - REACT_APP_BACKEND_URL=http://localhost:8000
  #   tty: true

  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: "*"
        DJANGO_SECRET_KEY: "*"
        DJANGO_CORS_ORIGIN_WHITELIST: "*"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/backend/
    expose:
      - 8000
    env_file:
      - ./settings/dev/.env.dev
    restart: always
